# Generated by Django 4.0.1 on 2022-02-19 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="like_user_set",
            field=models.ManyToManyField(
                blank=True, related_name="like_comment_set", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="PostLikes",
        ),
    ]
