# Generated by Django 4.0.1 on 2022-02-21 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0002_comment_like_user_set_delete_postlikes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postcomment",
            name="tag_set",
        ),
        migrations.AddField(
            model_name="postcomment",
            name="like_user_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="like_post_comment_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
