# Generated by Django 4.0.1 on 2022-02-21 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0003_remove_postcomment_tag_set_postcomment_like_user_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcomment",
            name="answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="PostAnswer_set",
                to="posts.post",
                verbose_name="원글",
            ),
        ),
        migrations.CreateModel(
            name="CommentReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CommentReplyAuthor_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="대댓글작성자",
                    ),
                ),
                (
                    "like_user_set",
                    models.ManyToManyField(
                        blank=True,
                        related_name="like_comment_reply_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="posts.comment"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
